name = "Diary"
license = "MIT"
licenselink = "/blob/master/LICENSE"
description = "Moments piled up. A simple, elegant blog theme."
homepage = "https://github.com/TRSWNCA"
tags = ["blog"]
features = ["mobile","elegant"]
min_version = "0.59.0"

[author]
  name = "trswnca"
  homepage = "https://github.com/TRSWNCA"


# If porting an existing theme
[original]
  name = "amazingrise"
  homepage = "https://amazingrise.net/"
  repo = "https://github.com/amazingrise/hugo-theme-diary"
